#pragma once

namespace hokee
{
constexpr char PROJECT_VERSION[]{"@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@.@GIT_COMMIT_HASH@"};
constexpr char PROJECT_VERSION_SHORT[]{"@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@"};

constexpr char PROJECT_DESCRIPTION[]{"@PROJECT_DESCRIPTION@"};

constexpr char PROJECT_HOMEPAGE_URL[]{"@PROJECT_HOMEPAGE_URL@"};
} // namespace hokee