name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-18.04, ubuntu-20.04]
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: Run Build
      run: bash build.sh ${{ matrix.config }}
    - name: Run Tests
      run: cd build/${{ matrix.config }}; ctest -C ${{ matrix.config }} --output-on-failure
    - name: Tar artifacts
      run: tar -cvzf homebanking_${{ matrix.os }}_${{ matrix.config }}.tar.gz bin/* testdata/*
    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }} ${{ matrix.config }}
        path: homebanking_${{ matrix.os }}_${{ matrix.config }}.tar.gz