name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash

    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-18.04, ubuntu-20.04]
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: bash build.sh ${{ matrix.config }}
    - name: Run CPack
      run: cd build/${{ matrix.config }}; cmake --build . --config ${{ matrix.config }} --target package --parallel
    - name: Run tests
      run: cd build/${{ matrix.config }}; ctest -C ${{ matrix.config }} --output-on-failure
    - uses: actions/upload-artifact@v2
      name: Upload packages
      with:
        name: ${{ matrix.os }}-${{ matrix.config }}-packages
        path: build/**/hokee-*
