name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-11, ubuntu-20.04]
        config: [Release]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Visual Studio shell
        if: ${{ matrix.os == 'windows-2022' }}
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      - name: Run build
        run: bash build.sh ${{ matrix.config }}
      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.config }} --output-on-failure
      - name: Run CPack
        if: ${{ matrix.config == 'Release' }}
        run: |
          cd build
          cmake --build . --config ${{ matrix.config }} --target package --parallel
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        if: ${{ matrix.config == 'Release' && matrix.os == 'windows-latest' }}
        with:
          age: '1 day'
      - name: Upload packages
        uses: actions/upload-artifact@v2
        if: ${{ matrix.config == 'Release' }}
        with:
          name: ${{ matrix.os }}-${{ matrix.config }}-packages
          path: build/hokee-*
